### PR TITLE
Added Deleting Courses and Assignments

### PR DESCRIPTION
**Pull request by EthanZhang15**

### CODE REVIEW

**Comment by allenjeffreywu** [comment]
This seems to be a duplicate of https://github.com/kiat/codeAssist/pull/81. Is this intentional?

**Comment by defkorean** [comment]
> This seems to be a duplicate of #81. Is this intentional?

We're going to review both pull requests. Pull Request #81 is related to the accidental push to main this past Sunday and I believe it was made before seeing Dr. Teymourian's message of pulling a fresh commit of the rollbacked main branch.

**Review by defkorean — COMMENTED** [review]
- Deleting all submissions work
- Deleting all assignments work
- Deleting a course works when there are no assignments
- Deleting a course doesn't work when assignments exist -> 500 status code

Additionally, after deleting all assignments the course can't be deleted for some reason.
Could potentially just be my machine getting this error, if anyone else gets this too please confirm.

**Review by hudsonwhipple — APPROVED** [review]
Found no errors! Looks Good after the comments above!

**Pull request merged**
